DELETE FROM WORKOUT;
DELETE FROM TRAINER;

INSERT INTO TRAINER (ID, NAME) VALUES (1000, 'Jack');

INSERT INTO WORKOUT (ID, TRAINER_ID, NAME) VALUES (1000, 1000, 'Test Workout 1');
INSERT INTO WORKOUT (ID, TRAINER_ID, NAME) VALUES (1001, 1000, 'Test Workout 2');